add files

diff --git a/service/test_script b/service/test_script
--- a/service/test_script
+++ b/service/test_script
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env ksh
 # author leidong
 
 TOP_DIR=${TOP_DIR:-$(cd $(dirname "$0")/.. && pwd)}
@@ -9,25 +9,55 @@ CMD_SH=$(which ksh 2>/dev/null)
 
 if [[ -d $UNIT_DIR ]]; then
     
-    source $UNIT_DIR/functions
+    . $UNIT_DIR/functions
 else
-    source $TOP_DIR/unit/functions
+    . $TOP_DIR/unit/functions
 fi
 
 [[ -f $SCRIPT_FILE  ]] || die $LINENO "Not Found $SCRIPT_FILE"
 [[ -f $ARGS_FILE  ]] || die $LINENO "Not Found $ARGS_FILE"
 
 
+## check ok result 
+function check_res {
+    local filename=$1
+    local exitcode=1
+
+    [[ -f $filename ]] || die "Not Found $filename file"
+    json_linenum=$(cat $filename | sed -n 's/^{\(.*\)}$/\1/p')
+    success_linenum=$(cat $filename | sed -n 's/^1|\(.*\)|SUCCESS$/\1/p' | egrep "100" )
+    [[ -n $json_linenum || -n $success_linenum ]] && exitcode=0
+    return $exitcode
+}
 ## exec spec script file 
 function _exec_ {
 
     local exec_script=$1
     local args="$2"
-    ## cd in script dir
-    exec_dir=$(dirname $exec_script)
+    local funcname=$3
+    local exec_dir=$(dirname $exec_script)
+    local datetime=$(date +"${TIMESTAMP_FORMAT}")
+    local inargs=
+    local is_ok=1
+    local log_file="/$LOG_DIR/${funcname}.log"
+    local log_file_tmp="/$LOG_DIR/.${funcname}.log.tmp"
+
     [[ -d $exec_dir ]] && cd $exec_dir/
-    $CMD_SH $exec_script $args &>>/$LOG_DIR/${funcname}.log
-    [[ $? -eq 0 ]] && passed "${funcname} script is passed" || failed "${funcname} script is failed"
+
+    for arg in $args
+    do
+        #inargs="$inargs '$arg'"
+        inargs="$inargs $arg"
+    done
+    printf "$datetime [SCRIPT: $funcname ARGS: $inargs] -- " >> $log_file 
+
+    [[ -f $log_file_tmp ]] && cat /dev/null > $log_file_tmp 
+    $CMD_SH $exec_script $inargs 2>&1 | tee -ai $log_file_tmp
+    is_ok=$?
+
+    check_res $log_file_tmp
+    [[ $? -eq 0  &&$is_ok -eq 0 ]] && passed " {{ ${funcname} ${inargs} }} script is passed" || failed "{{ ${funcname} ${inargs} }} script is failed"
+    cat $log_file_tmp >> $log_file
 }
 
 ## get specified function alise name eg host
@@ -98,7 +128,10 @@ function  exec_funcs {
                 has_options $nrname $SCRIPT_FILE $subcom
                 get_options_conf $nrname $SCRIPT_FILE $subcom outfunc 
             fi
-            
+
+            funcname=$(echo $outfunc | cut -d"=" -f2)
+            get_script_file $funcname exec_script
+
             has_args $nrname $ARGS_FILE $subcom
             if [[ $? -ne 0 ]]; then
                 warn $LINENO "Not Found $subcom args in [$nrname] group from $ARGS_FILE" 
@@ -106,21 +139,24 @@ function  exec_funcs {
             fi
 
             get_args_conf $nrname $ARGS_FILE $subcom outargs
-
-            funcname=$(echo $outfunc | cut -d"=" -f2)
-
-            get_script_file $funcname exec_script
-            args=$(echo $outargs | sed 's/[#|@]/ /g')
-
-            _exec_ $exec_script "$args"
+            outargs=$(echo $outargs | tr "!" " ")
+            for outarg in $outargs
+            do
+                args=$(echo $outarg | sed 's/[#@]/ /g')
+                _exec_ $exec_script "$args" $funcname
+            done
 
         done
     else
-        outfuncs=$(get_options_conf $nrname $SCRIPT_FILE all)
+        get_options_conf $nrname $SCRIPT_FILE all outfuncs
+        outfuncs=$(echo "$outfuncs" | tr "!" " ")
+
         for outfunc in $outfuncs
         do
             subcom=$(echo $outfunc | cut -d"=" -f1) 
             funcname=$(echo $outfunc | cut -d"=" -f2) 
+
+            get_script_file $funcname exec_script
 
             has_args $nrname $ARGS_FILE $subcom
             if [[ $? -ne 0 ]] ; then
@@ -129,10 +165,12 @@ function  exec_funcs {
             fi
 
             get_args_conf $nrname $ARGS_FILE $subcom outargs
-            args=$(echo $outargs | sed 's/[#|@]/ /g')
-
-            get_script_file $funcname exec_script
-            _exec_ $exec_script "$args"
+            outargs=$(echo $outargs | tr "!" " ")
+            for outarg in $outargs
+            do
+                args=$(echo $outarg | sed 's/[#@]/ /g')
+                _exec_ $exec_script "$args" $funcname
+            done
         done
     fi
 }
@@ -140,8 +178,11 @@ function  exec_funcs {
 ## exec pd.conf file in all groups
 ## all main functions
 function all_exec_funcs {
-    local nrnames=$(get_selects_conf $SCRIPT_FILE)
-    [[ -n $nrnames ]] || die $LINENO "Not Found select in $SCRIPT_FILE"
+
+    get_selects_conf $SCRIPT_FILE nrnames
+    nrnames=$(echo $nrname | tr "!" " ")
+    [[ -n "$nrnames" ]] || die $LINENO "Not Found select in $SCRIPT_FILE"
+
     for nrname in $nrnames
     do
         exec_funcs $nrname
@@ -161,12 +202,13 @@ function full_exec_funcs {
         if [[ -n  $fullscriptname ]] ; then
             get_args_conf "shell" $ARGS_FILE "$fullscriptname" outfuncs || die $LINENO "Not Found  $fullscriptname from [shell] group in $ARGS_FILE"
         else
-            outfuncs=$(get_args_conf "shell" $ARGS_FILE "all") || die $LINENO "Not Found [shell] group in $ARGS_FILE"
+            get_args_conf "shell" $ARGS_FILE "all" outfuncs || die $LINENO "Not Found [shell] group in $ARGS_FILE"
         fi
     else
         die $LINENO "Not Found [shell] group in $ARGS_FILE"
     fi
 
+    outfuncs=$(echo $outfuncs | tr "!" " ")
     for outfunc in $outfuncs
     do
         funcname=$(echo $outfunc | cut -d"=" -f1)
@@ -175,7 +217,7 @@ function full_exec_funcs {
 
         get_script_file $funcname exec_script
 
-        _exec_ $exec_script "$args"
+        _exec_ $exec_script "$args" $funcname
     done
 }
 
diff --git a/unit/functions b/unit/functions
--- a/unit/functions
+++ b/unit/functions
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env ksh
 # we always start with no errors
 ERROR=0
 PASS=0
@@ -15,6 +15,7 @@ function log {
     local xtrace=$(set +o | grep xtrace)
     set +o xtrace
 
+    local datetime=$(date +"${TIMESTAMP_FORMAT}")  
     local res=$1
     shift 1
     local msg="$@"
@@ -23,18 +24,25 @@ function log {
         logfile="failed.log"
     fi 
     logfile=$LOG_DIR/$logfile 
-    echo -n $(date +"${TIMESTAMP_FORMAT}") "[SCRIPT: $0 PID: $$] -- " >> $logfile
+    printf "$datetime [SCRIPT: $0 PID: $$] -- " >> $logfile
     echo $msg 2>&1 | tee -ai $logfile
     $xtrace
     return $exitcode
 }
 
 function passed {
+    local exitcode=$?
     local xtrace=$(set +o | grep xtrace)
     set +o xtrace
 
-    local lineno=$(caller 0 | awk '{print $1}')
-    local function=$(caller 0 | awk '{print $2}')
+    if [[ `basename $(echo $SHELL)` = 'bash' ]]; then
+        local lineno=$(caller 0 | awk '{print $1}')
+        local function=$(caller 0 | awk '{print $2}')
+    else
+        local lineno=$LINENO
+        local function="passed"
+    fi
+
     local msg="$1"
     if [ -z "$msg" ]; then
         msg="OK"
@@ -47,13 +55,20 @@ function passed {
 }
 
 function failed {
+    local exitcode=$?
     local xtrace=$(set +o | grep xtrace)
     set +o xtrace
 
-    local lineno=$(caller 0 | awk '{print $1}')
-    local function=$(caller 0 | awk '{print $2}')
+    if [[ `basename $(echo $SHELL)` = 'bash' ]]; then
+        local lineno=$(caller 0 | awk '{print $1}')
+        local function=$(caller 0 | awk '{print $2}')
+    else
+        local lineno=$LINENO
+        local function="failed"
+    fi
+
     local msg="$1"
-    FAILED_FUNCS+="$function:L$lineno\n"
+    FAILED_FUNCS="$FAILED_FUNCS $function:L$lineno\n"
     log 1 "ERROR: $function:L$lineno!" "$msg"
     ERROR=$((ERROR+1))
 
@@ -64,20 +79,28 @@ function failed {
 function assert_equal {
     local xtrace=$(set +o | grep xtrace)
     set +o xtrace
-    local lineno=`caller 0 | awk '{print $1}'`
-    local function=`caller 0 | awk '{print $2}'`
+    
+    if [[ `basename $(echo $SHELL)` = 'bash' ]]; then
+        local lineno=$(caller 0 | awk '{print $1}')
+        local function=$(caller 0 | awk '{print $2}')
+    else
+        local lineno=$LINENO
+        local function="assert_equal"
+    fi
+    
+
+    local lineno=$LINENO
+
     local msg=$3
     if [[ "$1" != "$2" ]]; then
-        FAILED_FUNCS+="$function:L$lineno\n"
-        echo "ERROR: $1 != $2 in $function:L$lineno!"
-        echo "  $msg"
+        FAILED_FUNCS=" $FAILED_FUNCS $function:L$lineno\n"
+        log 1 "ERROR: $1 != $2 in $function:L$lineno!" "  $msg"
         ERROR=$((ERROR+1))
     else
         PASS=$((PASS+1))
-        echo "$function:L$lineno - ok"
+        log 0 "$function:L$lineno - ok"
     fi
     $xtrace
-    return $exitcode
 }
 
 function report_results {
@@ -92,7 +115,6 @@ function report_results {
         exit 1
     fi
     $xtrace
-    return $exitcode
 }
 
 
@@ -102,13 +124,20 @@ function get_selects_conf {
     set +o xtrace
 
     local confname=$1
-    local nrname=$2
+    local var=$2
+    local nrname=$3
 
     #rets=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" )
-    rets=$(awk NF $confname| sed -n 's/^\[\(.*\)\]$/\1/p')
-    [[ ! -n $nrname ]] && echo $rets || echo $rets |egrep "$nrname"
+    if [[ ! -n $nrname ]] ; then
+        rets=$(awk NF $confname| sed -n 's/^\[\(.*\)\]$/\1/p')
+    else
+        rets=$(awk NF $confname| sed -n 's/^\[\(.*\)\]$/\1/p' | egrep "$nrname")
+    fi
+
+    rets=$(echo $rets | tr " " "!")
+    eval $var="$rets"
+
     $xtrace
-    return $exitcode
 }
 
 ## get you specifiled version options in object.conf
@@ -122,10 +151,10 @@ function get_options_version_conf {
     local var=$5
 
     #ret=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=" | egrep "_$version=")
-    ret=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}_${version}=")
+    ret=$(awk NF $confname  | awk '/\['`echo $nrname`'\]/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}_${version}=")
     eval "$var=$ret"
+
     $xtrace
-    return $exitcode
 }
 
 ## get you specifiled options in object.conf
@@ -138,14 +167,16 @@ function get_options_conf {
     local var=$4
 
     if [[ $subcom != 'all' ]] ; then
-        ret=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=")
-        eval "$var=$ret"
+        rets=$(awk NF $confname  | awk '/\['`echo $nrname`'\]/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=")
+        rets=$(echo $rets | tr " " "!")
+        eval $var="$rets"
     else
-        rets=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" )
-        echo $rets
+        rets=$(awk NF $confname  | awk '/\['`echo $nrname`'\]/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" )
+        rets=$(echo $rets | tr " " "!")
+        eval $var="$rets"
+        #echo $rets
     fi
     $xtrace
-    return $exitcode
 }
 
 ## get you specifiled arg in args.conf
@@ -162,18 +193,22 @@ function get_args_conf {
 
     if [[ $subcom != 'all' ]] ; then
         if [[ $nrname != "shell" ]] ; then
-            rets=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=" | awk -F"=" '{print $2}')
-            eval "$var=$rets"
+            rets=$(awk NF $confname  | awk '/\['`echo $nrname`'\]/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=" | awk -F"=" '{print $2}')
+            rets=$(echo $rets | tr " " "!")
+            eval $var="$rets"
         else
-            rets=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=" )
-            eval "$var=$rets"
+            rets=$(awk NF $confname  | awk '/\['`echo $nrname`'\]/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=" )
+            rets=$(echo $rets | tr " " "!")
+            eval $var="$rets"
         fi
     else
-        rets=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" )
-        echo $rets
+        rets=$(awk NF $confname  | awk '/\['`echo $nrname`'\]/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" )
+        rets=$(echo $rets | tr " " "!")
+        eval $var="$rets"
+        #echo $rets
     fi
+
     $xtrace
-    return $exitcode
 }
 
 ## has you specifiled selects in object.conf
@@ -187,6 +222,7 @@ function has_selects_conf {
     rets=$(awk NF $confname | sed -n 's/^\[\(.*\)\]$/\1/p' | egrep "^$nrname")
     [[ -n $rets ]] && return 0 || return 1
     #[[ ! -n $selectname ]] && echo $rets || echo $rets |egrep "$selectname"
+
     $xtrace
 }
 
@@ -199,7 +235,7 @@ function has_options_conf {
     local subcom=$3
 
     if [[ $subcom != 'all' ]] ; then
-        ret=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=")
+        ret=$(awk NF $confname  | awk '/\['`echo $nrname`'\]/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=")
         [[ -n $ret ]] && return 0 || return 1
     else
         return 0
@@ -218,8 +254,9 @@ function has_options_version_conf {
     local version=$4
 
     #ret=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}=" | egrep "_$version=" )
-    ret=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}_${version}=" )
+    ret=$(awk NF $confname  | awk '/\['`echo $nrname`'\]/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^${subcom}_${version}=" )
     [[ -n $ret ]] && return 0 || return 1
+
     $xtrace
 }
 
@@ -233,7 +270,8 @@ function has_args_conf {
     local var=$4
 
     [[ -f $confname ]] || echo "Not Found config $confname"
-    rets=$(awk NF $confname  | awk '/'`echo $nrname`'/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^$funcname" )
+    rets=$(awk NF $confname  | awk '/\['`echo $nrname`'\]/{while(getline)if($0!~/\[/) print;else exit;}' | sed '/^\s*#/d' | egrep "=" | egrep "^$funcname" )
     [[ -n $rets ]] && return 0 || return 1
+
     $xtrace
 }
